### ISSUE TITLE
why dont it run?

### ISSUE THREAD

**Issue by jamieduk** [nathan-149/Elon-Musk-Tracker-Script#1]
./tracker.py
Traceback (most recent call last):
  File "./tracker.py", line 7, in <module>
    from geopy.geocoders import Nominatim
ImportError: No module named geopy.geocoders

**Comment by TheLime03** [comment]
run cmd and type :
`pip install geopy`

**Comment by TheLime1** [comment]
> ./tracker.py Traceback (most recent call last): File "./tracker.py", line 7, in from geopy.geocoders import Nominatim ImportError: No module named geopy.geocoders

run cmd and type :
`pip install geopy`
